### ISSUE TITLE
Bayesian bandits

### ISSUE THREAD

**Issue by rawls238** [rawls238/Bandits.jl#1]

**Comment by rawls238** [comment]
Should have one that is specifically for conjugate priors and another which uses Racing Thompson sampling to handle non conjugate priors (https://arxiv.org/pdf/1708.04781.pdf)

**Comment by v-i-s-h** [comment]
Hi,
I have been developing a very similar package for over a year: You can find it here - https://github.com/v-i-s-h/MAB.jl
Initially, I was calling it Bandits.jl ( https://github.com/v-i-s-h/Bandits.jl still redirects to my renamed MAB package), but when I tried to register METADATA, I came to know your package is using the name.

My package includes 20+ different bandit algorithms, 7 arm models. Right now, I'm working on a new feature called 'Experiments' (https://github.com/v-i-s-h/MAB.jl/tree/vish-dev/src/Experiments) with the aim of reproducible research.

I was watching this repo for some time and couldn't see much activity here. I would like to politely ask that if you are not planning to develop your package further, can I use "Bandits.jl" package name?
Also, will you be interested in collaborating?

With Regards,
Vishnu Raj

**Comment by rawls238** [comment]
Hi Vishnu,

I'm planning on working on this substantially in about half a month's time so I'd prefer to keep the name (if for whatever reason I'm unable to make substantial progress then, will be happy to transfer over the name of the repo). I would be interested in collaborating though, I'd like to make substantial progress on some of the things I was interested in implementing but perhaps we can merge the packages at that point?

Sorry for the inconvenience.

Best,
Guy

**Comment by v-i-s-h** [comment]
Thanks.
